spring.application.name=api-gateway
server.port=8080

# Route 1: /users/** -> user-service (8081)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# Route 2: /payments/** -> payment-service (8082)
spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**
